version: "3.4"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.0.2
    ports:
      - "80:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  api:
    container_name: api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - redis
    environment:
      NODE_ENV:
      JWT_SECRET:
      MONGO_URI:
      REDIS_HOST:
      REDIS_PORT:
      REDIS_PASSWORD:
      CLIENT_HOSTS:
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.${DOMAIN}`)
      - traefik.http.services.api.loadbalancer.server.port=4000

  mongo:
    container_name: mongo
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:

  redis:
    container_name: redis
    image: redis:5-alpine
